### ISSUE TITLE
Write a PHP SDK for merchants

### ISSUE THREAD

**Issue by ruphy** [italia/18app-php-sdk#1]
The documentation, test files and a description of the test environment are available here:

[Progetto18app.zip](https://github.com/italia/18app-dotnet-sdk/files/1356869/Progetto18app.zip)
[WS_VerificaVoucher.zip](https://github.com/italia/18app-dotnet-sdk/files/1356870/WS_VerificaVoucher.zip)
[Linee Guida Esercenti_ottobre 2016.pdf](https://github.com/italia/18app-dotnet-sdk/files/1356867/Linee.Guida.Esercenti_ottobre.2016.pdf)

Qui spiegazioni su 18app: https://developers.italia.it/it/18app/

**Comment by ste80pa** [comment]
Hi, i've created a fork with my proposal for this library. 
- Provided test case suite
- Code coverage support
- Documentation by Doxygen
- Composer installable package or standalone trought autoload.php
- Continuous integration ready

**Comment by alranel** [comment]
Hello @ste80pa, and thank you for your contribution. We decided to merge pull request #2 because the hackathon rules asked to submit pull requests and it was preselected during the Fast Rabbit evaluation phase. It's also a bit more documented and simpler thank your codebase. However, your code is well written and I like all the add-ons you provided (Doxygen, Composer, code coverage etc.) so if you're willing to contribute those to the current codebase you're absolutely welcome.
